name: bookmarks
description: A Flutter project. for Ian's Bookmarks scheme

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cron: ^0.5.1
  flutter:
    sdk: flutter
  flutter_settings_screens: ^0.3.3-null-safety+2
  http: ^0.13.5
  receive_sharing_intent: ^1.4.5
  sqflite: ^2.2.2
  test: ^1.21.4
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: false
  remove-alpha_ios: true
  image_path: "images/logo.png"
  web:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - images/
