= Bookmarks

For those who use multiple browsers, synching browser bookmarks
is not a convenient option.

This Flutter project is part of Ian's Bookmarks scheme.

== Status

**Note:** At present this is a demo only, and while the UI
works for some domains of "works", there is NO PERSISTENCE
so please don't spend time typing URLs in here.
Hopefully it will soon interact with a datastore backend.

There are two main pages so far:

* ListPage - main - start of a list-based main page that will
** launch a browser if you tap on a URL;
** invoke the Add page from the FAB
* EditPage - page for editing a bookmark.

The EditPage can be started when any other app does a "Share"
of a web link and you choose to open with Bookmarks,
even if the app isn't running. This works thanks to the
receive_sharing_intent plugin from pub.dev.

ListPage should also handle long press on a bookmark, with a popup menu
for edit, delete (any other?).

A future version will have a local database,
backed either with Ian's Java-based backend or with FireBase.

And there'll need to be a settings page for the
server info and other options.
