= Bookmarks

For those who use multiple browsers, synching browser bookmarks
is not an option.

This Flutter project is part of Ian's Bookmarks scheme.
Hopefully it will someday interact with a datastore backend.

== Status

**Note:** At present this is a demo only, and while the UI
works for some domains of "works", there is NO PERSISTENCE
so please don't spend time typing URLs in here.

There are two main pages so far:

* ListPage - main - start of a list-based main page that will
** launch a browser if you tap on a URL;
** invoke the Add page from the FAB
* EditPage - page for editing a bookmark.

At present the main() invokes the ListPage directly;
if you change main() to go directly to EditPage, then
the EditPage can be started when any other app does a "Share"
of a web link, even if the app isn't running.

ListPage should also handle long press on a bookmark, with a popup menu
for edit, delete (any other?).

The "share intent" stuff in EditPage.initState() should be moved
into main, and should fire off an EditPage when a request comes in.

A future version will have a local database,
backed either with Ian's Java-based backend or with FireBase.

And there'll need to be a settings page for the
server info and other options.